org.gradle.jvmargs=-Xms1024m -Xmx4096m
android.useAndroidX=true
android.enableJetifier=true
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
# Avoid Kotlin incremental cache crash when project is on D: and pub-cache on C:
kotlin.incremental=false
kotlin.compiler.execution.strategy=in-process
